### ISSUE TITLE
Discussion: Sollten die Berechtigungen abstand haben?

### ISSUE THREAD

**Issue by peterLERNSAX** [peterLERNSAX/softwaredd#33]
![image](https://user-images.githubusercontent.com/113515583/219666324-b76b8945-90b3-4849-aaec-7a38c67d489c.png)

Sollten die Icons so sein wie jetzt oder sollen die alle sauber untereinander sein?

```text
abc +
abcdc +
cb +
```
oder

```text
abc   +
abcdc +
cb    +
```

**Comment by jessicaLERNSAX** [comment]
Gute Frage, finde es sieht so wie es jetzt ist, schon recht unsortiert aus, aber wenn man beides bündig macht, sieht es vielleicht auch blöd aus? Vielleicht könnte Jonas das mal einstellen und zeigen.

**Comment by jonasLERNSAX** [comment]
ALLES BLEIBT SO WIE ES IST. OB DU HIER BIST UND NICHT!
