### ISSUE TITLE
Clean up readme.md

### ISSUE THREAD

**Issue by peterLERNSAX** [peterLERNSAX/softwaredd#58]
- `readme.md` should not contain any documentation
- documentation should be moved to `docs` (maybe under `docs/phasen`)
- link to docs
- generell information about the project

**Comment by Daniel-olaO** [comment]
Hey, I'm new to OS and I would like to work on the issue

**Comment by jessicaLERNSAX** [comment]
sad story

**Comment by jonasLERNSAX** [comment]
> Hey, I'm new to OS and I would like to work on the issue

Oh no, don't do this!
